version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/ui"
      schedule:
          interval: "daily"
          open-pull-requests-limit: 5
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "daily"
