version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  # envoy:
  #   container_name: envoy
  #   build:
  #     context: ./cmd/envoy
  #   hostname: envoy
  #   networks:
  #     - docker_network
  #   ports:
  #     - 9901:9901
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./cmd/nginx
  #   hostname: nginx
  #   networks:
  #     - docker_network
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - <<: *services-volume
  #       source: keys/
  #       target: /etc/cert/keys/
  # node:
  #   container_name: node
  #   build:
  #     context: ./ui
  #   hostname: node
  #   volumes:
  #     - <<: *services-volume
  #       source: ./keys
  #       target: /usr/src/keys
  #   networks:
  #     - docker_network
  #   ports:
  #     - 443:3000
  # api:
  #   container_name: go-server
  #   build:
  #     context: ./
  #   links:
  #     - postgres:app_db
  #   volumes:
  #     - <<: *services-volume
  #       source: ./keys
  #       target: /var/lib/apid/keys
  #   ports:
  #     - 10112:10112
  #   hostname: go-server
  #   networks:
  #     - docker_network
  #   environment:
  #     DB_ADDR: app_db
  #     DB_PORT: 5432
  #     DB_USER: table_admin
  #     DB_PASSWORD: ${USERPWD}
  #     DB_NAME: blog
  #   depends_on:
  #     - postgres
  postgres:
    container_name: postgres
    build:
      # dockerfile: ./cmd/db/dockerfile
      context: ./cmd/db
    volumes:
      - <<: *services-volume
        # source: ${HOST}/postgres
        source: /home/data/postgres2
        target: /var/lib/postgres
    ports:
      - 5432:5432
      # - 8342:8342
    hostname: postgres
    networks:
      - docker_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: blog
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
