version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  go:
    container_name: go
    build:
      context: ../
    links:
      - postgres:app_db
    ports:
      - "8888:8888"
    networks:
      - docker_network
    environment:
      DB_ADDR: app_db
      DB_PORT: 5432
      DB_USER: table_admin
      DB_PASSWORD: ${USERPWD}
      DB_NAME: pBlog
    depends_on:
      - postgres
  postgres:
    container_name: postgresTest
    build:
      context: ../db
    volumes:
      - <<: *services-volume
        source: /tmp/postgres
        target: /var/lib/postgres
      #- "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
    expose:
      - 5432
    networks:
      - docker_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: pBlog
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${USERPWD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
