name: Check mergeable

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  go_ci:
    strategy:
      matrix:
        go-version: [go1.13, go1.14, go1.15]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Use Go ${{ matrix.go-version }}
        uses: cedrickring/golang-action${{ matrix.go-version}}@1.6.0

  node_storybook_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ui/
      - run: npm run build-storybook --if-present
        working-directory: ui/

  node_react_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ui/
      - run: npm run build --if-present
        working-directory: ui/
